# Generated by Django 2.2 on 2019-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Done'), (2, 'Archived')], default=0),
            preserve_default=False,
        ),
    ]
